# Generated by Django 2.2.1 on 2019-06-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipaddress', models.CharField(max_length=50, verbose_name='主机名称')),
                ('alert', models.CharField(max_length=100, verbose_name='报警名称')),
            ],
            options={
                'verbose_name': '当前zabbix平台所有报警',
                'verbose_name_plural': '当前zabbix平台所有报警',
                'db_table': 'now_alert',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='alert_level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='报警关键字')),
                ('level', models.CharField(max_length=50, verbose_name='报警级别')),
            ],
            options={
                'verbose_name': '报警级别设置',
                'verbose_name_plural': '报警级别设置',
                'db_table': 'alert_level',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='now_alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipaddress', models.CharField(max_length=50, verbose_name='主机名称')),
                ('alert', models.CharField(max_length=100, verbose_name='报警名称')),
            ],
            options={
                'verbose_name': '当前zabbix平台所有报警',
                'verbose_name_plural': '当前zabbix平台所有报警',
                'db_table': '2_now_alert',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdat', models.CharField(max_length=50, verbose_name='创建时间')),
                ('updatedat', models.CharField(max_length=50, verbose_name='更新时间')),
                ('hostname', models.CharField(max_length=50, verbose_name='主机名称')),
                ('tigger', models.CharField(max_length=100, verbose_name='报警名称')),
                ('media', models.CharField(max_length=100, verbose_name='通知媒介')),
                ('tel_log', models.CharField(max_length=100, verbose_name='电话日志记录')),
                ('queren', models.CharField(max_length=100, verbose_name='是否确认')),
            ],
            options={
                'verbose_name': '电话报警相关记录',
                'verbose_name_plural': '电话报警相关记录',
                'db_table': 'university',
                'managed': True,
            },
        ),
    ]
