# Generated by Django 2.2.1 on 2019-06-07 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aaaa', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jenkins_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=50)),
                ('job_name', models.CharField(max_length=50)),
                ('fabu_all_count', models.CharField(max_length=20)),
                ('prd_success', models.CharField(max_length=20)),
                ('prd_abort', models.CharField(max_length=20)),
                ('prd_faill', models.CharField(max_length=20)),
                ('fat_success', models.CharField(max_length=20)),
                ('fat_abort', models.CharField(max_length=20)),
                ('fat_faill', models.CharField(max_length=20)),
                ('all_success', models.CharField(max_length=20)),
                ('all_faill', models.CharField(max_length=20)),
                ('all_abort', models.CharField(max_length=20)),
            ],
        ),
    ]
